<?php

function returnSettings()
{
	return array(
	array('Name' => 'QueryPort', 'Help' => 'Needs to be an unused port like 30000', 'Default' => '27015', 'File' => 'shard_config.ini'),
	array('Name' => 'GamePort', 'Help' => 'Needs to be an unused port like 30000', 'Default' => '7777', 'File' => 'shard_config.ini'),
	array('Name' => 'RCONPort', 'Help' => 'Needs to be an unused port like 30000', 'Default' => '27020', 'File' => 'shard_config.ini'),
	array('Name' => 'battle_eye', 'Help' => 'Determines whether or not the server enables Battle Eye anti cheat', 'Default' => 'false', 'File' => 'shard_config.ini', 'Value_Type' => 't/f'),
	array('Name' => 'SessionName', 'Help' => 'Define the name of the Ark server', 'Default' => 'Ark_Server', 'File' => 'GameUserSettings.ini', 'Header' => '[SessionSettings]'),
	array('Name' => 'ServerPassword', 'Help' => 'Define the password for the Ark server', 'Default' => 'password', 'File' => 'GameUserSettings.ini', 'Header' => '[ServerSettings]'),
	array('Name' => 'MaxPlayers', 'Help' => 'Define the number of players that can join the server', 'Default' => '10', 'File' => 'shard_config.ini'),
	array('Name' => 'PreventDownloadSurvivors', 'Help' => '', 'Default' => 'false', 'File' => 'GameUserSettings.ini', 'Header' => '[ServerSettings]', 'Value_Type' => 't/f'),
	array('Name' => 'PreventUploadSurvivors', 'Help' => '', 'Default' => 'false', 'File' => 'GameUserSettings.ini', 'Header' => '[ServerSettings]', 'Value_Type' => 't/f'),
	array('Name' => 'PreventDownloadItems', 'Help' => '', 'Default' => 'false', 'File' => 'GameUserSettings.ini', 'Header' => '[ServerSettings]', 'Value_Type' => 't/f'),
	array('Name' => 'PreventUploadItems', 'Help' => '', 'Default' => 'false', 'File' => 'GameUserSettings.ini', 'Header' => '[ServerSettings]', 'Value_Type' => 't/f'),
	array('Name' => 'PreventDownloadDinos', 'Help' => '', 'Default' => 'false', 'File' => 'GameUserSettings.ini', 'Header' => '[ServerSettings]', 'Value_Type' => 't/f'),
	array('Name' => 'PreventUploadDinos', 'Help' => '', 'Default' => 'false', 'File' => 'GameUserSettings.ini', 'Header' => '[ServerSettings]', 'Value_Type' => 't/f'),
	array('Name' => 'ShowMapPlayerLocation', 'Help' => '', 'Default' => 'true', 'File' => 'GameUserSettings.ini', 'Header' => '[ServerSettings]', 'Value_Type' => 't/f'),
	array('Name' => 'AllowThirdPersonPlayer', 'Help' => '', 'Default' => 'true', 'File' => 'GameUserSettings.ini', 'Header' => '[ServerSettings]', 'Value_Type' => 't/f'),
	array('Name' => 'ServerCrosshair', 'Help' => '', 'Default' => 'true', 'File' => 'GameUserSettings.ini', 'Header' => '[ServerSettings]', 'Value_Type' => 't/f'),
	array('Name' => 'NonPermanentDisease', 'Help' => '', 'Default' => 'true', 'File' => 'GameUserSettings.ini', 'Header' => '[ServerSettings]', 'Value_Type' => 't/f'),
	array('Name' => 'AllowAnyoneBabyImprintCuddle', 'Help' => '', 'Default' => 'true', 'File' => 'GameUserSettings.ini', 'Header' => '[ServerSettings]', 'Value_Type' => 't/f'),
	array('Name' => 'DisableStructureDecayPvE', 'Help' => '', 'Default' => 'true', 'File' => 'GameUserSettings.ini', 'Header' => '[ServerSettings]', 'Value_Type' => 't/f'),
	array('Name' => 'OverrideStructurePlatformPrevention', 'Help' => '', 'Default' => 'true', 'File' => 'GameUserSettings.ini', 'Header' => '[ServerSettings]', 'Value_Type' => 't/f'),
	array('Name' => 'bAllowPlatformSaddleMultiFloors', 'Help' => '', 'Default' => 'true', 'File' => 'GameUserSettings.ini', 'Header' => '[ServerSettings]', 'Value_Type' => 't/f'),
	array('Name' => 'AllowCrateSpawnsOnTopOfStructures', 'Help' => '', 'Default' => 'true', 'File' => 'GameUserSettings.ini', 'Header' => '[ServerSettings]', 'Value_Type' => 't/f'),
	array('Name' => 'AllowHitMarkers', 'Help' => '', 'Default' => 'true', 'File' => 'GameUserSettings.ini', 'Header' => '[ServerSettings]', 'Value_Type' => 't/f'),
	array('Name' => 'AllowFlyerCarryPvE', 'Help' => '', 'Default' => 'true', 'File' => 'GameUserSettings.ini', 'Header' => '[ServerSettings]', 'Value_Type' => 't/f'),
	array('Name' => 'AllowFlyingStaminaRecovery', 'Help' => '', 'Default' => 'true', 'File' => 'GameUserSettings.ini', 'Header' => '[ServerSettings]', 'Value_Type' => 't/f'),
	array('Name' => 'bAllowUnlimitedRespecs', 'Help' => '', 'Default' => 'true', 'File' => 'GameUserSettings.ini', 'Header' => '[ServerSettings]', 'Value_Type' => 't/f'),
	array('Name' => 'DestroyUnconnectedWaterPipes', 'Help' => "After two days real-time the pipes will auto-destroy if unconnected to any non-pipe (directly or indirectly) and no allied player is nearby.", 'Default' => 'true', 'File' => 'GameUserSettings.ini', 'Header' => '[ServerSettings]', 'Value_Type' => 't/f'),
	array('Name' => 'DisableImprintDinoBuff', 'Help' => "Use this to disable the Dino Imprinting-Player Stat Bonus, if you don't like it (where whomever specifically imprinted on the Dino, and Raised it to have an Imprinting Quality, gets extra Damage/Resistance buff).", 'Default' => 'false', 'File' => 'GameUserSettings.ini', 'Header' => '[ServerSettings]', 'Value_Type' => 't/f'),
	array('Name' => 'ForceFlyerExplosives', 'Help' => '', 'Default' => 'false', 'File' => 'GameUserSettings.ini', 'Header' => '[ServerSettings]', 'Value_Type' => 't/f'),
	array('Name' => 'PreventSpawnAnimations', 'Help' => '', 'Default' => 'false', 'File' => 'GameUserSettings.ini', 'Header' => '[ServerSettings]', 'Value_Type' => 't/f'),
	array('Name' => 'RCONEnabled', 'Help' => '', 'Default' => 'false', 'File' => 'GameUserSettings.ini', 'Header' => '[ServerSettings]', 'Value_Type' => 't/f'),
	array('Name' => 'ShowFloatingDamageText', 'Help' => '', 'Default' => 'false', 'File' => 'GameUserSettings.ini', 'Header' => '[ServerSettings]', 'Value_Type' => 't/f'),
	array('Name' => 'ServerAdminPassword', 'Help' => 'Define the password for the Server Admin for use with RCON', 'Default' => 'adminpassword', 'File' => 'GameUserSettings.ini', 'Header' => '[ServerSettings]'),
	array('Name' => 'AllowRaidDinoFeeding', 'Help' => "To allow your Server's Titanosaurs to be permanently tamed (namely allow them to be Fed) However, note that TheIsland currently only spawns 3 Titanosaurs whatsoever, so 3 Tamed ones would ultimately block any more Wild ones from spawning.", 'Default' => 'false', 'File' => 'GameUserSettings.ini', 'Header' => '[ServerSettings]', 'Value_Type' => 't/f'),
	array('Name' => 'PersonalTamedDinosSaddleStructureCost', 'Help' => 'determines the amount of dino slots a platform saddle will use towards the tribe dino limit. Introduced in patch 265.0', 'Default' => '19', 'File' => 'GameUserSettings.ini', 'Header' => '[ServerSettings]'),
	array('Name' => 'MaxPlatformSaddleStructureLimit', 'Help' => 'Changes the maximum number of platformed-creatures/rafts allowed on the ARK (a potential performance cost) Example: MaxPlatformSaddleStructureLimit=10 would only allow 10 platform saddles / rafts across the entire ark', 'Default' => '40', 'File' => 'GameUserSettings.ini', 'Header' => '[ServerSettings]', 'Value_Type' => 'numerical'),
	array('Name' => 'TheMaxStructuresInRange', 'Help' => '', 'Default' => '10500.00000', 'File' => 'GameUserSettings.ini', 'Header' => '[ServerSettings]', 'Value_Type' => 'numerical'),
	array('Name' => 'StructurePreventResourceRadiusMultiplier', 'Help' => 'This adjusts the range at which player placed structures will affect resources from respawning', 'Default' => '1.000000', 'File' => 'GameUserSettings.ini', 'Header' => '[ServerSettings]', 'Value_Type' => 'numerical'),
	array('Name' => 'TribeNameChangeCooldown', 'Help' => '', 'Default' => '15.000000', 'File' => 'GameUserSettings.ini', 'Header' => '[ServerSettings]', 'Value_Type' => 'numerical'),
	array('Name' => 'AllowHideDamageSourceFromLogs', 'Help' => '', 'Default' => 'false', 'File' => 'GameUserSettings.ini', 'Header' => '[ServerSettings]', 'Value_Type' => 't/f'),
	array('Name' => 'RaidDinoCharacterFoodDrainMultiplier', 'Help' => '', 'Default' => '1.000000', 'File' => 'GameUserSettings.ini', 'Header' => '[ServerSettings]', 'Value_Type' => 'numerical'),
	array('Name' => 'PvEDinoDecayPeriodMultiplier', 'Help' => '', 'Default' => '1.000000', 'File' => 'GameUserSettings.ini', 'Header' => '[ServerSettings]', 'Value_Type' => 'numerical'),
	array('Name' => 'KickIdlePlayersPeriod', 'Help' => '', 'Default' => '3600.000', 'File' => 'GameUserSettings.ini', 'Header' => '[ServerSettings]', 'Value_Type' => 'numerical'),
	array('Name' => 'PerPlatformMaxStructuresMultiplier', 'Help' => '', 'Default' => '1.000000', 'File' => 'GameUserSettings.ini', 'Header' => '[ServerSettings]', 'Value_Type' => 'numerical'),
	array('Name' => 'AutoSavePeriodMinutes', 'Help' => '', 'Default' => '15.000000', 'File' => 'GameUserSettings.ini', 'Header' => '[ServerSettings]', 'Value_Type' => 'numerical'),
	array('Name' => 'ListenServerTetherDistanceMultiplier', 'Help' => '', 'Default' => '1.0000000', 'File' => 'GameUserSettings.ini', 'Header' => '[ServerSettings]', 'Value_Type' => 'numerical'),
	array('Name' => 'MaxTamedDinos', 'Help' => 'Max tamed dinos total on the server (for everyone)', 'Default' => '5000.00000', 'File' => 'GameUserSettings.ini', 'Header' => '[ServerSettings]', 'Value_Type' => 'numerical'),
	array('Name' => 'RCONServerGameLogBuffer', 'Help' => '', 'Default' => '600.000', 'File' => 'GameUserSettings.ini', 'Header' => '[ServerSettings]', 'Value_Type' => 'numerical'),
	array('Name' => 'XPMultiplier', 'Help' => '', 'Default' => '2.0', 'File' => 'GameUserSettings.ini', 'Header' => '[ServerSettings]', 'Value_Type' => 'numerical'),
	array('Name' => 'TamingSpeedMultiplier', 'Help' => '', 'Default' => '3.0', 'File' => 'GameUserSettings.ini', 'Header' => '[ServerSettings]', 'Value_Type' => 'numerical'),
	array('Name' => 'HarvestAmountMultiplier', 'Help' => '', 'Default' => '1.5', 'File' => 'GameUserSettings.ini', 'Header' => '[ServerSettings]', 'Value_Type' => 'numerical'),
	array('Name' => 'OverrideOfficialDifficulty', 'Help' => '', 'Default' => '5.0', 'File' => 'GameUserSettings.ini', 'Header' => '[ServerSettings]', 'Value_Type' => 'numerical'),
	array('Name' => 'OxygenSwimSpeedStatMultiplier', 'Help' => '', 'Default' => '1.2000000', 'File' => 'GameUserSettings.ini', 'Header' => '[ServerSettings]', 'Value_Type' => 'numerical'),
	array('Name' => 'EggHatchSpeedMultiplier', 'Help' => '', 'Default' => '10.0', 'File' => 'Game.ini', 'Header' => '[/script/shootergame.shootergamemode]', 'Value_Type' => 'numerical'),
	array('Name' => 'bPvEDisableFriendlyFire', 'Help' => 'Disable Friendly Fire on PvE servers only', 'Default' => 'true', 'File' => 'Game.ini', 'Header' => '[/script/shootergame.shootergamemode]', 'Value_Type' => 't/f'),
	array('Name' => 'bDisableFriendlyFire', 'Help' => 'Disable friendly fire on PvP enabled servers', 'Default' => 'true', 'File' => 'Game.ini', 'Header' => '[/script/shootergame.shootergamemode]', 'Value_Type' => 't/f'),
	array('Name' => 'serverPVE', 'Help' => '', 'Default' => 'true', 'File' => 'Game.ini', 'Header' => '[ServerSettings]', 'Value_Type' => 't/f'),
	array('Name' => 'BabyMatureSpeedMultiplier', 'Help' => '', 'Default' => '40.0', 'File' => 'Game.ini', 'Header' => '[/script/shootergame.shootergamemode]', 'Value_Type' => 'numerical'),
	array('Name' => 'MatingIntervalMultiplier', 'Help' => '', 'Default' => '0.15', 'File' => 'Game.ini', 'Header' => '[/script/shootergame.shootergamemode]', 'Value_Type' => 'numerical'),
	array('Name' => 'BabyCuddleIntervalMultiplier', 'Help' => '', 'Default' => '0.0625', 'File' => 'Game.ini', 'Header' => '[/script/shootergame.shootergamemode]', 'Value_Type' => 'numerical'),
	array('Name' => 'bDisableStructurePlacementCollision', 'Help' => '', 'Default' => 'true', 'File' => 'Game.ini', 'Header' => '[/script/shootergame.shootergamemode]', 'Value_Type' => 't/f'),
	array('Name' => 'Server_Map', 'Help' => 'Map name "TheIsland", "TheCenter", "ScorchedEarth_P", "Ragnarok", "Aberration_P", "Extinction"', 'Default' => 'TheIsland', 'File' => 'shard_config.ini'),
	//Server Mandatory (These need to be in the config files for the server to run. The user doesn't really care about their settings)
	array('Name' => 'MasterAudioVolume', 'Default' => '1.000000', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'MusicAudioVolume', 'Default' => '1.000000', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'SFXAudioVolume', 'Default' => '1.000000', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'VoiceAudioVolume', 'Default' => '1.000000', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'UIScaling', 'Default' => '1.000000', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'UIQuickbarScaling', 'Default' => '0.650000', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'CameraShakeScale', 'Default' => '0.650000', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bFirstPersonRiding', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bThirdPersonPlayer', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bShowStatusNotificationMessages', 'Default' => 'True', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'TrueSkyQuality', 'Default' => '0.000000', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'FOVMultiplier', 'Default' => '1.000000', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'GroundClutterDensity', 'Default' => '0.000000', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bFilmGrain', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bMotionBlur', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bUseDistanceFieldAmbientOcclusion', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bUseSSAO', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bShowChatBox', 'Default' => 'True', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bCameraViewBob', 'Default' => 'True', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bInvertLookY', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bFloatingNames', 'Default' => 'True', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bChatBubbles', 'Default' => 'True', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bHideServerInfo', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bJoinNotifications', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bCraftablesShowAllItems', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bLocalInventoryItemsShowAllItems', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bLocalInventoryCraftingShowAllItems', 'Default' => 'True', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bRemoteInventoryItemsShowAllItems', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bRemoteInventoryCraftingShowAllItems', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bRemoteInventoryShowEngrams', 'Default' => 'True', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'LookLeftRightSensitivity', 'Default' => '1.000000', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'LookUpDownSensitivity', 'Default' => '1.000000', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'GraphicsQuality', 'Default' => '1', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'ActiveLingeringWorldTiles', 'Default' => '1', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'ClientNetQuality', 'Default' => '3', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'LastServerSearchType', 'Default' => '0', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'LastServerSort', 'Default' => '2', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'LastPVESearchType', 'Default' => '-1', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'LastDLCTypeSearchType', 'Default' => '-1', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'LastServerSortAsc', 'Default' => 'True', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'LastAutoFavorite', 'Default' => 'True', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'LastServerSearchHideFull', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'LastServerSearchProtected', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'HideItemTextOverlay', 'Default' => 'True', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bQuickToggleItemNames', 'Default' => 'True', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bDistanceFieldShadowing', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'LODScalar', 'Default' => '0.780000', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bToggleToTalk', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'HighQualityMaterials', 'Default' => 'True', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'HighQualitySurfaces', 'Default' => 'True', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bTemperatureF', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bDisableTorporEffect', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bChatShowSteamName', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bChatShowTribeName', 'Default' => 'True', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bReverseTribeLogOrder', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'EmoteKeyBind1', 'Default' => '0', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'EmoteKeyBind2', 'Default' => '0', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bNoBloodEffects', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bLowQualityVFX', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bSpectatorManualFloatingNames', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bSuppressAdminIcon', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bUseSimpleDistanceMovement', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bDisableMeleeCameraSwingAnims', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bHighQualityAnisotropicFiltering', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bUseLowQualityLevelStreaming', 'Default' => 'True', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bPreventInventoryOpeningSounds', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bPreventItemCraftingSounds', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bPreventHitMarkers', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bPreventCrosshair', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bPreventColorizedItemNames', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bHighQualityLODs', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bExtraLevelStreamingDistance', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bEnableColorGrading', 'Default' => 'True', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'DOFSettingInterpTime', 'Default' => '0.000000', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bDisableBloom', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bDisableLightShafts', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'LastJoinedSessionPerCategory', 'Default' => '', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'LastJoinedSessionPerCategory', 'Default' => '', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'LastJoinedSessionPerCategory', 'Default' => '', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'LastJoinedSessionPerCategory', 'Default' => '', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'LastJoinedSessionPerCategory', 'Default' => '', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'LastJoinedSessionPerCategory', 'Default' => '', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'LastJoinedSessionPerCategory', 'Default' => '', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'LastJoinedSessionPerCategory', 'Default' => '', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'LastJoinedSessionPerCategory', 'Default' => '', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bDisableMenuTransitions', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bEnableInventoryItemTooltips', 'Default' => 'True', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bRemoteInventoryShowCraftables', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bNoTooltipDelay', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'LocalItemSortType', 'Default' => '0', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'LocalCraftingSortType', 'Default' => '0', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'RemoteItemSortType', 'Default' => '0', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'RemoteCraftingSortType', 'Default' => '0', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'VersionMetaTag', 'Default' => '1', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'ShowExplorerNoteSubtitles', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'DisableMenuMusic', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'DisableDefaultCharacterItems', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bHideFloatingPlayerNames', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bHideGamepadItemSelectionModifier', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bToggleExtendedHUDInfo', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'PlayActionWheelClickSound', 'Default' => 'True', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'MaxAscensionLevel', 'Default' => '0', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bHostSessionHasBeenOpened', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bForceTPVCameraOffset', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bDisableTPVCameraInterpolation', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bFPVClimbingGear', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bFPVGlidingGear', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'Gamma1', 'Default' => '2.200000', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'Gamma2', 'Default' => '3.000000', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'AmbientSoundVolume', 'Default' => '1.000000', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bUseVSync', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'MacroCtrl0', 'Default' => '', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'MacroCtrl1', 'Default' => '', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'MacroCtrl2', 'Default' => '', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'MacroCtrl3', 'Default' => '', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'MacroCtrl4', 'Default' => '', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'MacroCtrl5', 'Default' => '', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'MacroCtrl6', 'Default' => '', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'MacroCtrl7', 'Default' => '', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'MacroCtrl8', 'Default' => '', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'MacroCtrl9', 'Default' => '', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'ResolutionSizeX', 'Default' => '1280', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'ResolutionSizeY', 'Default' => '720', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'LastUserConfirmedResolutionSizeX', 'Default' => '1280', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'LastUserConfirmedResolutionSizeY', 'Default' => '720', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'WindowPosX', 'Default' => '-1', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'WindowPosY', 'Default' => '-1', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'bUseDesktopResolutionForFullscreen', 'Default' => 'False', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'FullscreenMode', 'Default' => '2', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'LastConfirmedFullscreenMode', 'Default' => '2', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'Version', 'Default' => '5', 'Header' => '[/Script/ShooterGame.ShooterGameUserSettings]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'sg.ResolutionQuality', 'Default' => '100', 'Header' => '[ScalabilityGroups]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'sg.ViewDistanceQuality', 'Default' => '3', 'Header' => '[ScalabilityGroups]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'sg.AntiAliasingQuality', 'Default' => '3', 'Header' => '[ScalabilityGroups]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'sg.ShadowQuality', 'Default' => '3', 'Header' => '[ScalabilityGroups]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'sg.PostProcessQuality', 'Default' => '3', 'Header' => '[ScalabilityGroups]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'sg.TextureQuality', 'Default' => '3', 'Header' => '[ScalabilityGroups]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'sg.EffectsQuality', 'Default' => '3', 'Header' => '[ScalabilityGroups]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'sg.TrueSkyQuality', 'Default' => '3', 'Header' => '[ScalabilityGroups]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'sg.GroundClutterQuality', 'Default' => '3', 'Header' => '[ScalabilityGroups]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'sg.IBLQuality', 'Default' => '1', 'Header' => '[ScalabilityGroups]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'sg.HeightFieldShadowQuality', 'Default' => '3', 'Header' => '[ScalabilityGroups]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	array('Name' => 'sg.GroundClutterRadius', 'Default' => '10000',  'Header' => '[ScalabilityGroups]', 'File' => 'GameUserSettings.ini', 'Help' => '', 'Value_Type' => 'server_mandatory'),
	);
}
?>

