<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRxJS6jC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRxJS6jC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRxJS6jC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRxJS6jC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRxJS6jC\App_KernelDevDebugContainer([
    'container.build_hash' => 'RxJS6jC',
    'container.build_id' => '89ae14b1',
    'container.build_time' => 1578432487,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRxJS6jC');
